
@url = http://localhost:4400

GET http://localhost:4400/photosapi

###

GET http://localhost:4400/photosapi/1

###
GET http://localhost:4400/employeesapi

###
GET {{url}}/employeesapi/1

###
POST {{url}}/login
Content-Type: application/json

{
  "email":"john@vanarts.com",
  "password":"234561"
}

###
POST {{url}}/signup
Content-Type: application/json

{

  "email": "dafs",
  "password": "asfd"
}

###

PUT {{url}}/updateUser
Content-Type: application/json

{
  "UserID":3,
  "email": "e@e.com",
  "password": 1234
}


###

GET {{url}}/user/3